# Generated by Django 6.0.5 on 2026-05-20 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exchange",
            options={
                "ordering": ["name"],
                "verbose_name": "Exchange",
                "verbose_name_plural": "Exchanges",
            },
        ),
    ]
