# Generated by Django 6.0.5 on 2026-05-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exchange_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_markets', to='core.asset')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='core.exchange')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_markets', to='core.asset')),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('exchange', 'base_asset', 'quote_asset')},
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='core.market')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('market', 'timestamp')},
            },
        ),
    ]
