# Generated by Django 6.0.5 on 2026-05-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asset_market_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['base_asset__symbol', 'quote_asset__symbol']},
        ),
        migrations.RemoveField(
            model_name='market',
            name='symbol',
        ),
    ]
