# Generated by Django 5.0.6 on 2024-05-23 18:21

from typing import Any

from django.db import migrations


def populate_markets(apps: Any, schema_editor: Any) -> None:
    """Populates the Market table with data for Binance and Foxbit exchanges."""
    Asset = apps.get_model("core", "Asset")
    Exchange = apps.get_model("core", "Exchange")
    Market = apps.get_model("core", "Market")

    brl_asset, created = Asset.objects.get_or_create(
        symbol="BRL", defaults={"name": "Brazilian Real"}
    )

    exchanges_to_populate = ["Binance", "Foxbit"]
    for exchange_name in exchanges_to_populate:
        exchange = Exchange.objects.get(name=exchange_name)
        assets = Asset.objects.exclude(symbol="BRL")
        for asset in assets:
            Market.objects.get_or_create(
                base_asset=asset,
                quote_asset=brl_asset,
                exchange=exchange,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_populate_assets"),
    ]

    operations = [
        migrations.RunPython(populate_markets),
    ]
