# Generated by Django 6.0.5 on 2026-05-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_populate_markets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='volume',
        ),
    ]
